baseURL = "https://b1d0ws.github.io/"
languageCode = "en-us"
title = "b1d0ws"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "just a n00b"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "just a n00b blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[[params.social]]
name = "email"
url  = "mailto:eduardobido@yahoo.com.br"

[[params.social]]
name = "linkedin"
url  = "https://www.linkedin.com/in/eduardo-bido-541430193/"

[languages]
  [languages.en]
    title = "b1d0ws"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoMark     = " "
      logoText = "/home/b1d0ws"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
 [menu]
 [[menu.main]]
    identifier = "posts"
    name       = "posts"
    url        = "posts/"
  [[menu.main]]
    identifier = "write-ups"
    name       = "write-ups"
    url        = "write-ups/"
  [[menu.main]]
    identifier = "whoami"
    name       = "whoami"
    url        = "whoami/"
  
  
  
